return {
	['Sets'] = {
		['Primary'] = {
			[1] = 'Button_1',
			[2] = 'Button_8',
			[33] = 'Button_2',
			[32] = 'Button_7',
			[31] = 'Button_3',
			[45] = 'Button_5',
			[15] = 'Button_6',
		},
		['Movement'] = {
			[1] = 'Button_4',
		},
	},
	['LastBackup'] = 1779680004,
	['Characters'] = {
		['Project Lazarus_Napharious'] = {
			['Windows'] = {
				[1] = {
					['ButtonSize'] = 3,
					['Sets'] = {
						[1] = 'Primary',
					},
					['Locked'] = true,
					['Height'] = 163,
					['Visible'] = true,
					['Pos'] = {
						['y'] = 644,
						['x'] = 977,
					},
					['Theme'] = 'Moonlight',
					['Width'] = 518,
					['FPS'] = 0,
					['Font'] = 8,
				},
			},
		},
	},
	['Version'] = 7,
	['Buttons'] = {
		['Button_4'] = {
			['CachedLabel'] = 'Nav Target (bca)',
			['Cmd'] = '/bca //nav id ${Target.ID}',
			['Label'] = 'Nav Target (bca)',
		},
		['Button_5'] = {
			['labelMidY'] = 2,
			['IconLua'] = '',
			['Label'] = 'Clear Targets',
			['CachedLabel'] = 'Clear Targets',
			['ShowLabel'] = true,
			['ButtonColorRGB'] = '0,190,0',
			['CachedCoolDownTimer'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 23000.855,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['Cmd'] = '/cleartargets',
			['UpdateRate'] = 0,
			['CachedCountDown'] = 0,
			['EvaluateLabel'] = false,
			['labelMidX'] = 0,
		},
		['Button_7'] = {
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 23000.855,
			['TimerType'] = 'Seconds Timer',
			['Label'] = 'PAUSE (all)',
			['CachedLabel'] = 'PAUSE (all)',
			['ShowLabel'] = true,
			['Cooldown'] = 0,
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['Cmd'] = '/bcaa //multi ; /twist off ; /mqp on',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
		},
		['Button_8'] = {
			['Cmd'] = '/debuffson',
			['Label'] = 'DeBUFF',
			['TimerType'] = 'Seconds Timer',
			['ShowLabel'] = true,
			['Cooldown'] = 0,
		},
		['Button_1'] = {
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 23000.855,
			['TimerType'] = 'Seconds Timer',
			['Label'] = 'DoTs',
			['CachedLabel'] = 'DoTs',
			['ShowLabel'] = true,
			['Cooldown'] = 0,
			['labelMidX'] = 2,
			['labelMidY'] = 8,
			['Cmd'] = '/dotson',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
		},
		['Button_2'] = {
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 23000.855,
			['TimerType'] = 'Seconds Timer',
			['Label'] = 'UNPAUSE(all)',
			['CachedLabel'] = 'UNPAUSE(all)',
			['ShowLabel'] = true,
			['Cooldown'] = 0,
			['labelMidX'] = 0,
			['labelMidY'] = 8,
			['Cmd'] = '/bcaa //mqp off',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
		},
		['Button_3'] = {
			['CachedToggleLocked'] = false,
			['CachedLastRan'] = 23000.855,
			['TimerType'] = 'Seconds Timer',
			['Label'] = 'BURN (all)',
			['CachedLabel'] = 'BURN (all)',
			['ShowLabel'] = true,
			['Cooldown'] = 0,
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['Cmd'] = '/bcaa //burn\n/timed 500 /bcaa //burn',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
		},
		['Button_6'] = {
			['labelMidY'] = 2,
			['CachedLastRan'] = 23000.855,
			['IconLua'] = '',
			['Label'] = 'NAV Target',
			['CachedLabel'] = 'NAV Target',
			['ShowLabel'] = true,
			['Cooldown'] = 0,
			['Cmd'] = '/nav target',
			['TimerType'] = 'Seconds Timer',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['CachedToggleLocked'] = false,
			['EvaluateLabel'] = false,
			['UpdateRate'] = 0,
			['labelMidX'] = 0,
		},
	},
}