return {
	['Characters'] = {
		['Project Lazarus_Jebisy'] = {
			['Windows'] = {
				[1] = {
					['Width'] = 317,
					['Visible'] = true,
					['FPS'] = 0,
					['ButtonSize'] = 3,
					['Locked'] = true,
					['Sets'] = {
						[1] = 'Primary',
					},
					['Height'] = 230,
					['Pos'] = {
						['y'] = 576,
						['x'] = 1464,
					},
				},
			},
		},
		['Project Lazarus_Napharious'] = {
			['Windows'] = {
				[1] = {
					['Visible'] = true,
					['Width'] = 315,
					['Height'] = 232,
					['Pos'] = {
						['y'] = 574,
						['x'] = 979,
					},
					['Sets'] = {
						[1] = 'Primary',
					},
					['Font'] = 8,
					['ButtonSize'] = 3,
					['Locked'] = false,
					['Theme'] = 'Moonlight',
					['FPS'] = 0,
				},
			},
		},
	},
	['Buttons'] = {
		['Button_8'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 8,
			['CachedLastRan'] = 155457.712,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'DeBUFF',
			['CachedCountDown'] = 0,
			['Cmd'] = '/debuffson',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'DeBUFF',
		},
		['Button_14'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 8,
			['CachedLastRan'] = 155457.712,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'Anchor',
			['CachedCountDown'] = 0,
			['Cmd'] = '/anchoron',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'Anchor',
		},
		['Button_15'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.712,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'Anchor OFF',
			['CachedCountDown'] = 0,
			['Cmd'] = '/anchoroff',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'Anchor OFF',
		},
		['Button_10'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.712,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'nav target',
			['CachedCountDown'] = 0,
			['Cmd'] = '/nav target',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'nav target',
		},
		['Button_9'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.712,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'NAV NAPH',
			['CachedCountDown'] = 0,
			['Cmd'] = '/target Napharious\n/nav target',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'NAV NAPH',
		},
		['Button_16'] = {
			['labelMidX'] = 3,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['Cmd'] = '/bark poknowledge',
			['Label'] = 'Marr POK',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'Marr POK',
		},
		['Button_11'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 8,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'CliickIt',
			['CachedCountDown'] = 0,
			['Cmd'] = '/clickit /not|me',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'CliickIt',
		},
		['Button_7'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'PAUSE (all)',
			['CachedCountDown'] = 0,
			['Cmd'] = '/bcaa //multi ; /twist off ; /mqp on',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'PAUSE (all)',
		},
		['Button_5'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['IconLua'] = '',
			['EvaluateLabel'] = false,
			['ShowLabel'] = true,
			['Cmd'] = '/cleartargets',
			['UpdateRate'] = 0,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['CachedLabel'] = 'Clear Targets',
			['Label'] = 'Clear Targets',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['CachedToggleLocked'] = false,
			['ButtonColorRGB'] = '0,190,0',
		},
		['Button_12'] = {
			['labelMidX'] = 5,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'CT Low',
			['CachedCountDown'] = 0,
			['Cmd'] = '',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'CT Low',
		},
		['Button_13'] = {
			['labelMidX'] = 3,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'CT High',
			['CachedCountDown'] = 0,
			['Cmd'] = '',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'CT High',
		},
		['Button_6'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'CT MyTarget',
			['CachedCountDown'] = 0,
			['Cmd'] = '/cleartargets usemytarget',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'CT MyTarget',
		},
		['Button_1'] = {
			['labelMidX'] = 2,
			['labelMidY'] = 8,
			['CachedLastRan'] = 155457.712,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'DoTs',
			['CachedCountDown'] = 0,
			['Cmd'] = '/dotson',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'DoTs',
		},
		['Button_2'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 8,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'UNPAUSE(all)',
			['CachedCountDown'] = 0,
			['Cmd'] = '/bcaa //mqp off',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'UNPAUSE(all)',
		},
		['Button_3'] = {
			['labelMidX'] = 0,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['CachedCoolDownTimer'] = 0,
			['Label'] = 'BURN (all)',
			['CachedCountDown'] = 0,
			['Cmd'] = '/bcaa //burn\n/timed 500 /bcaa //burn',
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'BURN (all)',
		},
		['Button_4'] = {
			['Cmd'] = '/bca //nav id ${Target.ID}',
			['Label'] = 'Nav Target (bca)',
			['CachedLabel'] = 'Nav Target (bca)',
		},
		['Button_18'] = {
			['Cooldown'] = 0,
			['TimerType'] = 'Seconds Timer',
			['Cmd'] = '/target Benevolent\n/nav target',
			['ShowLabel'] = true,
			['Label'] = 'NAV SHM',
		},
		['Button_17'] = {
			['labelMidX'] = 3,
			['labelMidY'] = 2,
			['CachedLastRan'] = 155457.713,
			['TimerType'] = 'Seconds Timer',
			['Cooldown'] = 0,
			['ShowLabel'] = true,
			['Cmd'] = '/spawnmaster uplist',
			['Label'] = 'UP LIST',
			['CachedCountDown'] = 0,
			['CachedCoolDownTimer'] = 0,
			['CachedToggleLocked'] = false,
			['CachedLabel'] = 'UP LIST',
		},
	},
	['Sets'] = {
		['Primary'] = {
			[1] = 'Button_1',
			[2] = 'Button_8',
			[4] = 'Button_14',
			[5] = 'Button_15',
			[8] = 'Button_10',
			[9] = 'Button_9',
			[10] = 'Button_16',
			[16] = 'Button_11',
			[18] = 'Button_18',
			[31] = 'Button_3',
			[32] = 'Button_7',
			[33] = 'Button_2',
			[42] = 'Button_13',
			[45] = 'Button_5',
			[43] = 'Button_12',
			[44] = 'Button_6',
			[37] = 'Button_17',
		},
		['Movement'] = {
			[1] = 'Button_4',
		},
	},
	['LastBackup'] = 1779826418,
	['Version'] = 7,
}